#!/bin/sh
cpu_arch="$(cat "/proc/cpuinfo" | grep "model name" | sed -n "1p" | awk -F ': ' '{print $2}')"
[ -z "${cpu_arch}" ] && cpu_arch="Rk3399 Dual-core Cortex-A72 up to 1.8GHz@Quad-core Cortex-A53 up to 1.4GHz"
cpu_cores="$(cat "/proc/cpuinfo" | grep "processor" | wc -l)"
sys_temp="$(awk "BEGIN{printf (\"%.1f\n\",$(cat /sys/class/thermal/thermal_zone0/temp)/1000) }")°C"
echo -n "${cpu_arch} x ${cpu_cores} (${sys_temp})"
